# Generated by Django 3.2.7 on 2021-10-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(verbose_name='description')),
                ('rating', models.IntegerField(default=0)),
                ('producer', models.CharField(max_length=100)),
                ('public_id', models.CharField(max_length=300)),
                ('release_month', models.IntegerField(default=0)),
            ],
        ),
    ]
