# Generated by Django 3.2.7 on 2021-10-13 11:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_rename_producer_movie_director'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='release_month',
        ),
        migrations.AddField(
            model_name='movie',
            name='release_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
