# Generated by Django 3.2.7 on 2021-10-13 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20211013_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
