# Generated by Django 3.2.7 on 2021-10-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_movie_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
