# Generated by Django 3.2.7 on 2021-10-13 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_movie_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='price',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='movie',
            name='user_id',
            field=models.IntegerField(default=1),
        ),
    ]
