# Generated by Django 3.2.7 on 2021-10-13 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_alter_movie_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='user_id',
            field=models.IntegerField(default=1),
        ),
    ]
