# Generated by Django 3.2.7 on 2021-11-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=33)),
                ('lastname', models.CharField(max_length=33)),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('password', models.CharField(max_length=103)),
                ('public_id', models.CharField(max_length=103)),
                ('number', models.IntegerField(default=0)),
            ],
        ),
    ]
