"""initial mig

Revision ID: 278f0064ef8e
Revises: 
Create Date: 2020-12-06 02:48:10.275178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '278f0064ef8e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('location', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'location')
    # ### end Alembic commands ###
