"""moves

Revision ID: f3a50a9d5dd7
Revises: 278f0064ef8e
Create Date: 2020-12-14 14:50:56.015973

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f3a50a9d5dd7'
down_revision = '278f0064ef8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('category', sa.String(length=50), nullable=True))
    op.add_column('product', sa.Column('image', sa.LargeBinary(), nullable=True))
    op.add_column('product', sa.Column('name', sa.String(length=50), nullable=True))
    op.add_column('product', sa.Column('purchases', sa.Integer(), nullable=True))
    op.add_column('product', sa.Column('quantity', sa.Integer(), nullable=True))
    op.add_column('product', sa.Column('short_description', sa.String(length=64), nullable=True))
    op.add_column('product', sa.Column('tags', sa.PickleType(), nullable=True))
    op.add_column('product', sa.Column('vendor_id', sa.Integer(), nullable=True))
    op.drop_constraint('product_ibfk_1', 'product', type_='foreignkey')
    op.create_foreign_key(None, 'product', 'user', ['vendor_id'], ['id'])
    op.drop_column('product', 'description')
    op.drop_column('product', 'user_id')
    op.add_column('user', sa.Column('cart', sa.PickleType(), nullable=True))
    op.add_column('user', sa.Column('referred_by', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'referred_by')
    op.drop_column('user', 'cart')
    op.add_column('product', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('product', sa.Column('description', mysql.VARCHAR(length=256), nullable=True))
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.create_foreign_key('product_ibfk_1', 'product', 'user', ['user_id'], ['id'])
    op.drop_column('product', 'vendor_id')
    op.drop_column('product', 'tags')
    op.drop_column('product', 'short_description')
    op.drop_column('product', 'quantity')
    op.drop_column('product', 'purchases')
    op.drop_column('product', 'name')
    op.drop_column('product', 'image')
    op.drop_column('product', 'category')
    # ### end Alembic commands ###
