# Generated by Django 2.2.19 on 2021-10-06 09:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=53)),
                ('date_created', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('receiver_id', models.IntegerField(default=0)),
                ('public_id', models.CharField(max_length=103)),
            ],
        ),
    ]
