# Generated by Django 3.2.7 on 2021-11-02 15:48

from django.db import migrations
from ..utils import run_sql_file


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(run_sql_file('bincom_test.sql'))
    ]
